name: Build project using muddler and upload artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Muddle
        uses: demonnic/build-with-muddler@main
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: CK
          path: build/tmp/

